# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7a0d5a858acea9a57cd9ee0c0927140cef4cf9ede443a17fa227c12e40a5c3a776fcc9beaf5c12c1bf6cc722590da0133594925528bbebd298379eea9e8aea7

test:
  secret_key_base: 27fb4815808b3133ae8a4e60b6f7ef08df59ee95825b82f960a540adf4beae5340a69a85766e08806518706d8d341970fe1737acea46731ca1c630d250de57f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
